/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 02:54:28 GMT 2024
 */
package org.mockito.internal.configuration.injection;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mockito.internal.configuration.injection.PropertyAndSetterInjection;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class PropertyAndSetterInjection_ESTest extends PropertyAndSetterInjection_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test00() throws Throwable {
        PropertyAndSetterInjection propertyAndSetterInjection0 = new PropertyAndSetterInjection();
    }
}
