/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 06 16:17:47 GMT 2024
 */
package com.fasterxml.jackson.core.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.core.io.NumberInput;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class NumberInput_ESTest extends NumberInput_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test000() throws Throwable {
        NumberInput.parseBigDecimal((char[]) null);
    }

    @Test(timeout = 4000)
    public void test011() throws Throwable {
        char[] charArray0 = new char[1];
        NumberInput.parseBigDecimal(charArray0, (int) '-', (int) '-');
    }

    @Test(timeout = 4000)
    public void test022() throws Throwable {
        char[] charArray0 = new char[2];
        NumberInput.parseLong(charArray0, (int) 'J', (int) 'J');
    }

    @Test(timeout = 4000)
    public void test033() throws Throwable {
        NumberInput.parseBigDecimal(".");
    }

    @Test(timeout = 4000)
    public void test044() throws Throwable {
        NumberInput numberInput0 = new NumberInput();
    }

    @Test(timeout = 4000)
    public void test055() throws Throwable {
        char[] charArray0 = new char[10];
        int int0 = NumberInput.parseInt(charArray0, 0, 0);
    }

    @Test(timeout = 4000)
    public void test066() throws Throwable {
        char[] charArray0 = new char[18];
        int int0 = NumberInput.parseInt(charArray0, 0, 6);
    }

    @Test(timeout = 4000)
    public void test077() throws Throwable {
        char[] charArray0 = new char[5];
        int int0 = NumberInput.parseInt(charArray0, 2, 2);
    }

    @Test(timeout = 4000)
    public void test088() throws Throwable {
        char[] charArray0 = new char[8];
        int int0 = NumberInput.parseInt(charArray0, 3, 3);
    }

    @Test(timeout = 4000)
    public void test099() throws Throwable {
        char[] charArray0 = new char[8];
        int int0 = NumberInput.parseInt(charArray0, 0, 4);
    }

    @Test(timeout = 4000)
    public void test1010() throws Throwable {
        char[] charArray0 = new char[8];
        int int0 = NumberInput.parseInt(charArray0, 3, 5);
    }

    @Test(timeout = 4000)
    public void test1111() throws Throwable {
        char[] charArray0 = new char[8];
        int int0 = NumberInput.parseInt(charArray0, 0, 8);
    }

    @Test(timeout = 4000)
    public void test1212() throws Throwable {
        char[] charArray0 = new char[8];
        int int0 = NumberInput.parseInt(charArray0, 0, 7);
    }

    @Test(timeout = 4000)
    public void test1313() throws Throwable {
        char[] charArray0 = new char[12];
        int int0 = NumberInput.parseInt(charArray0, 0, 48);
    }

    @Test(timeout = 4000)
    public void test1414() throws Throwable {
        int int0 = NumberInput.parseInt("227");
    }

    @Test(timeout = 4000)
    public void test1515() throws Throwable {
        int int0 = NumberInput.parseInt("-7");
    }

    @Test(timeout = 4000)
    public void test1616() throws Throwable {
        NumberInput.parseInt("-");
    }

    @Test(timeout = 4000)
    public void test1717() throws Throwable {
        NumberInput.parseInt("-q;i(o3~2=sR");
    }

    @Test(timeout = 4000)
    public void test1818() throws Throwable {
        NumberInput.parseInt("@3~yi<Z>g\"%");
    }

    @Test(timeout = 4000)
    public void test1919() throws Throwable {
        NumberInput.parseInt("-D^");
    }

    @Test(timeout = 4000)
    public void test2020() throws Throwable {
        NumberInput.parseLong("&cU");
    }

    @Test(timeout = 4000)
    public void test2121() throws Throwable {
        NumberInput.parseInt("3p,5wZ");
    }

    @Test(timeout = 4000)
    public void test2222() throws Throwable {
        NumberInput.parseInt("0(b2");
    }

    @Test(timeout = 4000)
    public void test2323() throws Throwable {
        int int0 = NumberInput.parseInt("12");
    }

    @Test(timeout = 4000)
    public void test2424() throws Throwable {
        NumberInput.parseInt("60GKZsE");
    }

    @Test(timeout = 4000)
    public void test2525() throws Throwable {
        NumberInput.parseInt("31,5wk");
    }

    @Test(timeout = 4000)
    public void test2626() throws Throwable {
        int int0 = NumberInput.parseInt("3145");
    }

    @Test(timeout = 4000)
    public void test2727() throws Throwable {
        NumberInput.parseInt("315k");
    }

    @Test(timeout = 4000)
    public void test2828() throws Throwable {
        NumberInput.parseInt("2325+");
    }

    @Test(timeout = 4000)
    public void test2929() throws Throwable {
        NumberInput.parseLong("2.2250738585072012e-308");
    }

    @Test(timeout = 4000)
    public void test3030() throws Throwable {
        char[] charArray0 = new char[5];
        boolean boolean0 = NumberInput.inLongRange(charArray0, (int) '\u0000', (int) '\u0000', false);
    }

    @Test(timeout = 4000)
    public void test3131() throws Throwable {
        boolean boolean0 = NumberInput.inLongRange((char[]) null, 903, 903, false);
    }

    @Test(timeout = 4000)
    public void test3232() throws Throwable {
        char[] charArray0 = new char[10];
        charArray0[0] = '9';
        boolean boolean0 = NumberInput.inLongRange(charArray0, 0, 19, false);
    }

    @Test(timeout = 4000)
    public void test3333() throws Throwable {
        char[] charArray0 = new char[10];
        charArray0[0] = '_';
        boolean boolean0 = NumberInput.inLongRange(charArray0, 0, 19, true);
    }

    @Test(timeout = 4000)
    public void test3434() throws Throwable {
        boolean boolean0 = NumberInput.inLongRange("( kr_9jlUb'QNV[I,", false);
    }

    @Test(timeout = 4000)
    public void test3535() throws Throwable {
        boolean boolean0 = NumberInput.inLongRange("9uczL+oBzyBw\"fMc12F", true);
    }

    @Test(timeout = 4000)
    public void test3636() throws Throwable {
        boolean boolean0 = NumberInput.inLongRange("com.fasterxml.jackson.core.io.NumberInput", true);
    }

    @Test(timeout = 4000)
    public void test3737() throws Throwable {
        int int0 = NumberInput.parseAsInt("8", 8);
    }

    @Test(timeout = 4000)
    public void test3838() throws Throwable {
        int int0 = NumberInput.parseAsInt((String) null, 1);
    }

    @Test(timeout = 4000)
    public void test3939() throws Throwable {
        int int0 = NumberInput.parseAsInt("", (-1293));
    }

    @Test(timeout = 4000)
    public void test4040() throws Throwable {
        int int0 = NumberInput.parseAsInt("+O{,ur.b-O^WwX\"s", 100);
    }

    @Test(timeout = 4000)
    public void test4141() throws Throwable {
        int int0 = NumberInput.parseAsInt("-Sy+ShM<-;", 0);
    }

    @Test(timeout = 4000)
    public void test4242() throws Throwable {
        int int0 = NumberInput.parseAsInt("31,5wk", 937);
    }

    @Test(timeout = 4000)
    public void test4343() throws Throwable {
        long long0 = NumberInput.parseAsLong("+", 46);
    }

    @Test(timeout = 4000)
    public void test4444() throws Throwable {
        long long0 = NumberInput.parseAsLong((String) null, 102L);
    }

    @Test(timeout = 4000)
    public void test4545() throws Throwable {
        long long0 = NumberInput.parseAsLong("", 686L);
    }

    @Test(timeout = 4000)
    public void test4646() throws Throwable {
        long long0 = NumberInput.parseAsLong("-dw}?TDcHSVa", (-682));
    }

    @Test(timeout = 4000)
    public void test4747() throws Throwable {
        long long0 = NumberInput.parseAsLong("2.2250738585072012e-308", (-3257L));
    }

    @Test(timeout = 4000)
    public void test4848() throws Throwable {
        double double0 = NumberInput.parseAsDouble("", 0.0);
    }

    @Test(timeout = 4000)
    public void test4949() throws Throwable {
        double double0 = NumberInput.parseAsDouble((String) null, '\u0000');
    }

    @Test(timeout = 4000)
    public void test5050() throws Throwable {
        double double0 = NumberInput.parseAsDouble("2.2250738585072012e-308", 0.0);
    }
}
