/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 15 11:50:15 GMT 2023
 */
package org.apache.commons.compress.archivers.tar;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.PipedInputStream;
import java.nio.charset.IllegalCharsetNameException;
import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream;
import org.junit.runner.RunWith;

public class TarArchiveInputStreamTest {

    @Test(timeout = 4000)
    public void test00() throws Throwable {
        // Undeclared exception!
        try {
            TarArchiveInputStream.matches((byte[]) null, 6854);
            fail("Expecting exception: NullPointerException");
        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
        }
    }

    @Test(timeout = 4000)
    public void test11() throws Throwable {
        PipedInputStream pipedInputStream0 = new PipedInputStream();
        TarArchiveInputStream tarArchiveInputStream0 = new TarArchiveInputStream(pipedInputStream0, "Gx");
        tarArchiveInputStream0.getCurrentEntry();
        assertEquals(512, tarArchiveInputStream0.getRecordSize());
    }

    @Test(timeout = 4000)
    public void test22() throws Throwable {
        PipedInputStream pipedInputStream0 = new PipedInputStream();
        TarArchiveInputStream tarArchiveInputStream0 = new TarArchiveInputStream(pipedInputStream0, "Gx");
        MockFile mockFile0 = new MockFile(";(G3~{dE,6nC?1<", ",`mr");
        TarArchiveEntry tarArchiveEntry0 = new TarArchiveEntry(mockFile0);
        tarArchiveInputStream0.setCurrentEntry(tarArchiveEntry0);
        tarArchiveInputStream0.getCurrentEntry();
        assertEquals(512, tarArchiveInputStream0.getRecordSize());
    }

    @Test(timeout = 4000)
    public void test33() throws Throwable {
        PipedInputStream pipedInputStream0 = new PipedInputStream();
        TarArchiveInputStream tarArchiveInputStream0 = null;
        try {
            tarArchiveInputStream0 = new TarArchiveInputStream(pipedInputStream0, (-1501), 10240, "]V2X(Mp)");
            fail("Expecting exception: IllegalCharsetNameException");
        } catch (IllegalCharsetNameException e) {
            //
            // ]V2X(Mp)
        }
    }
}
